#!/bin/bash
#Nested if statements
#compare 2 numbers provided by the user and then check if the greater one is
#greater than 100

echo
if [ $1 -gt $2 ]
    then
        echo $1 is greater than $2
    else 
        echo $1 is less than $2
    fi
    if [ $1 -gt 100 ]
        then
            echo $1 is also greater than 100
        else
            echo $1 is less than 100
    fi
