#!/bin/bash

#Print appropriate message on disk space use

free_space=$( df -h | awk '{print $5}' | sort -n | tail -n 1 | sed 's/%//')

case $free_space in
	[1-5]*)
		echo Enough space available
		;;
	[6-7*])
		echo Space may be limited in future
		;;
	8*)
		echo You should clear old files soon
		;;
	9*)
		echo Soon there could be a serious problem
		;;
	*)
		echo Something is not quite right
		;;
esac
